build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
filter:
    paths: [app/*]
    excluded_paths: [bootstrap/*, config/*, database/*, public/*, resources/*, routes/*, storage/*, tests/*, vendor/*]
tools:
    php_analyzer: true
checks:
    php:
        code_rating: true
