name: Tests

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ${{ matrix.os }}
        env:
          DB_DATABASE: xetaravel_test
          DB_USERNAME: admin
          DB_PASSWORD: rootpass
        strategy:
            matrix:
                php: [8.2, 8.3, 8.4]
                os: [ubuntu-latest]

        name: PHP${{ matrix.php }} - ${{ matrix.os }}

        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: xetaravel_test
                    MYSQL_HOST: 127.0.0.1
                    MYSQL_USER: admin
                    MYSQL_PASSWORD: rootpass
                    MYSQL_ROOT_PASSWORD: rootpass
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: xdebug

            - name: Copy .env
              run: |
                php -r "file_exists('.env') || copy('.env.example', '.env');"

            - name: Install dependencies
              run: composer update --prefer-dist --no-interaction

            - name: Generate key
              run: php artisan key:generate


            - name: Publish vendors
              run: php artisan vendor:publish --provider="Xetaio\Editor\EditorServiceProvider"

            - name: Install JS
              run: |
                npm install
                npm run build

            - name: Execute tests
              run: php artisan test --coverage
              env:
                  DB_PORT: ${{ job.services.mysql.ports[3306] }}

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
              with:
                files: build/logs/coverage.xml
