name: Unit Tests

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 8.1
          - 8.0

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: xetaravel_test
        ports:
            - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@develop
        with:
          php-version: ${{ matrix.php }}

      - run: php -v

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover tests/vendor/temp/coverage.xml
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: tests/vendor/temp/coverage.xml