name: run-tests

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ${{ matrix.os }}
        env:
          DB_DATABASE: xetaravel_test
          DB_USERNAME: admin
          DB_PASSWORD: rootpass
        strategy:
            matrix:
                php: [8.0, 8.1]
                os: [ubuntu-latest]

        name: PHP${{ matrix.php }} - ${{ matrix.os }}

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: xetaravel_test
                    MYSQL_HOST: 127.0.0.1
                    MYSQL_USER: admin
                    MYSQL_PASSWORD: rootpass
                    MYSQL_ROOT_PASSWORD: rootpass
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Install dependencies
              run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/phpunit
              env:
                  DB_PORT: ${{ job.services.mysql.ports[3306] }}